# From https://github.com/geerlingguy/ansible-role-mysql.git
# Duplicated from replication.yml
# changed some vars to make sure we have a master-master replication
# We still use the same user / password

---
- name: Two way replication | Ensure replication user exists on master.
  mysql_user:
    name: "{{ mysql_replication_user.name }}"
    host: "{{ mysql_replication_user.host | default('%') }}"
    password: "{{ mysql_replication_user.password }}"
    priv: "{{ mysql_replication_user.priv | default('*.*:REPLICATION SLAVE') }}"
    state: present
  when: >
    (mysql_replication_role_bis == 'master')
    and mysql_replication_user
    and (mysql_replication_master_bis != '')

- name: Two way replication | Check slave replication status.
  mysql_replication: mode=getslave
  ignore_errors: true
  register: slave
  when: >
    mysql_replication_role_bis == 'slave'
    and (mysql_replication_master_bis != '')

- name: Two way replication | Check master replication status.
  mysql_replication: mode=getmaster
  delegate_to: "{{ mysql_replication_master_bis }}"
  register: master
  when: >
    ((slave.Is_Slave is defined and not slave.Is_Slave) or (slave.Is_Slave is not defined and slave|failed))
    and (mysql_replication_role_bis == 'slave')
    and (mysql_replication_master_bis != '')

- name: Two way replication | Configure replication on the slave.
  mysql_replication:
    mode: changemaster
    master_host: "{{ mysql_replication_master_bis }}"
    master_user: "{{ mysql_replication_user.name }}"
    master_password: "{{ mysql_replication_user.password }}"
    master_log_file: "{{ master.File }}"
    master_log_pos: "{{ master.Position }}"
  ignore_errors: True
  when: >
    ((slave.Is_Slave is defined and not slave.Is_Slave) or (slave.Is_Slave is not defined and slave|failed))
    and (mysql_replication_role_bis == 'slave')
    and (mysql_replication_master_bis != '')
    and mysql_replication_user

- name: Two way replication | Start replication.
  mysql_replication: mode=startslave
  when: >
    ((slave.Is_Slave is defined and not slave.Is_Slave) or (slave.Is_Slave is not defined and slave|failed))
    and (mysql_replication_role_bis == 'slave')
    and (mysql_replication_master_bis != '')